# Generated by Django 3.2.3 on 2022-05-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250, verbose_name='Code')),
                ('nom', models.CharField(max_length=250, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=250, verbose_name='Prénom')),
                ('cin', models.CharField(blank=True, max_length=250, null=True, verbose_name='CIN')),
                ('adresse', models.CharField(blank=True, max_length=250, null=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=250, null=True, verbose_name='Téléphone')),
                ('email', models.CharField(blank=True, max_length=250, null=True, verbose_name='e-mail')),
                ('niveau', models.CharField(blank=True, max_length=250, null=True, verbose_name='Niveau')),
                ('age', models.PositiveSmallIntegerField(blank=True, max_length=250, null=True, verbose_name='Age')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250, verbose_name='Code')),
                ('sujet', models.CharField(max_length=250, verbose_name='Sujet')),
                ('date_debut', models.DateTimeField(verbose_name='Date Début')),
                ('date_fin', models.DateTimeField(verbose_name='Date Fin')),
                ('nbre_place', models.PositiveSmallIntegerField(default=20, verbose_name='Nbre Place')),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Prix')),
                ('lieu', models.CharField(max_length=250, verbose_name='Lieu')),
                ('domaine', models.CharField(max_length=250, verbose_name='Domaine')),
                ('etat', models.CharField(blank=True, max_length=250, null=True, verbose_name='Etat')),
                ('participants', models.ManyToManyField(blank=True, null=True, related_name='formations', to='backend.Participant')),
            ],
        ),
    ]
