# Generated by Django 3.2.3 on 2022-05-08 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_participant_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formation',
            options={'ordering': ['-date_debut']},
        ),
        migrations.RemoveField(
            model_name='formation',
            name='participants',
        ),
        migrations.AlterField(
            model_name='formation',
            name='etat',
            field=models.CharField(blank=True, choices=[('O', 'Ouverte'), ('F', 'Fermée'), ('A', 'Annulée'), ('R', 'Reportée'), ('T', 'Terminée')], default='O', max_length=250, null=True, verbose_name='Etat'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='niveau',
            field=models.CharField(blank=True, choices=[('S', 'Sans'), ('P', 'Primaire'), ('C', 'Collégial'), ('S', 'Secondaire'), ('F', 'Formation Professionnelle'), ('U', 'Universitaire'), ('I', 'Ingénierie')], max_length=250, null=True, verbose_name='Niveau'),
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name='Date Inscription')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='backend.formation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='backend.participant')),
            ],
        ),
        migrations.AddField(
            model_name='formation',
            name='participant',
            field=models.ManyToManyField(through='backend.Inscription', to='backend.Participant'),
        ),
    ]
